
'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';
import { clearAllTranslations, getTrainRoutes } from '@/app/actions';
import { useToast } from '@/hooks/use-toast';
import { Loader2 } from 'lucide-react';

export default function AiDatabasePage({ onViewChange }: { onViewChange: (view: string) => void }) {
  const [isClearing, setIsClearing] = useState(false);
  const [routesExist, setRoutesExist] = useState(false);
  const { toast } = useToast();
  const router = useRouter();

  const handleViewTranslations = () => {
    onViewChange('translations');
  };
  
  useEffect(() => {
    getTrainRoutes().then(routes => {
        setRoutesExist(routes.length > 0)
    })
  }, [])

  const handleClearTranslations = async () => {
    setIsClearing(true);
    try {
      const result = await clearAllTranslations();
      toast({
        title: 'Success',
        description: result.message,
      });
    } catch (error) {
      toast({
        variant: 'destructive',
        title: 'Error',
        description: 'Failed to clear translations.',
      });
      console.error('Failed to clear translations:', error);
    } finally {
        setIsClearing(false);
    }
  };


  return (
    <div className="w-full">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-lg font-semibold md:text-2xl">AI Database</h1>
          <p className="text-muted-foreground">
            Explore and manage AI-generated data assets.
          </p>
        </div>
      </div>

      <div className="mt-4 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        <Card>
          <CardHeader>
            <CardTitle className="text-xl">AI Generated Text Translation</CardTitle>
            <CardDescription>
              View multilingual translations of train route data generated by AI.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-wrap gap-2">
            <Button onClick={handleViewTranslations} disabled={!routesExist} size="sm">
              View Translations
            </Button>
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button variant="destructive" disabled={isClearing || !routesExist} size="sm">
                    {isClearing && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                    {isClearing ? 'Clearing...' : 'Clear All'}
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                  <AlertDialogDescription>
                    This action cannot be undone. This will permanently delete all
                    translation data from the database.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Cancel</AlertDialogCancel>
                  <AlertDialogAction onClick={handleClearTranslations}>
                    Continue
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
